version: "3.9"

services:
  postgresql:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: sorawong
      POSTGRES_DB: yu-blog
